In [59]:
import pandas as pd

In [60]:
start = pd.read_csv("start_p2.csv")
final = pd.read_csv("final_p2.1.csv")

In [61]:
final

,Km,Vmax,activity,X,IR,pot2,ph,temp,dstr,lgCmin,...,TPSA1,TPSA2,TPSA,XLogP,MaxEStateIndex.1,MaxEStateIndex.2,MinPartialCharge.1,MaxPartialCharge.1,BCUT2D_CHGLO,id
0,NaN,NaN,1.0,NaN,NaN,NaN,6.2,25.0,NaN,NaN,...,52.0,40.5,NaN,NaN,5.992739,6.000000,-0.398299,0.037337,NaN,10001
1,NaN,NaN,1.0,NaN,NaN,NaN,5.8,35.0,NaN,NaN,...,40.5,29.5,20.3,0.4,6.000000,8.985509,-0.254557,-0.254557,-2.048433,10002
2,NaN,NaN,1.0,NaN,NaN,NaN,5.8,4.0,NaN,NaN,...,40.5,29.5,NaN,NaN,6.000000,8.985509,-0.254557,-0.254557,NaN,10003
3,NaN,NaN,1.0,NaN,NaN,NaN,5.8,4.0,NaN,NaN,...,40.5,29.5,NaN,NaN,6.000000,8.985509,-0.254557,-0.254557,NaN,10004
4,0.4913,0.004380,1.0,NaN,NaN,NaN,4,35.0,3.0,-1.00000,...,40.5,52.0,NaN,NaN,6.000000,5.992739,-0.254557,-0.254557,NaN,10005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9040,0.0350,0.060700,1.0,NaN,NaN,NaN,7.0,22.5,NaN,-2.39794,...,40.5,29.5,NaN,NaN,6.000000,8.985509,-0.254557,-0.254557,NaN,19041
9041,0.0360,0.058833,1.0,NaN,NaN,NaN,7.0,22.5,NaN,-2.39794,...,40.5,29.5,NaN,NaN,6.000000,8.985509,-0.254557,-0.254557,NaN,19042
9042,0.0330,0.053133,1.0,NaN,NaN,NaN,7.0,22.5,NaN,-2.39794,...,40.5,29.5,NaN,NaN,6.000000,8.985509,-0.254557,-0.254557,NaN,19043
9043,0.0310,0.049750,1.0,NaN,NaN,NaN,7.0,22.5,NaN,-2.39794,...,40.5,29.5,NaN,NaN,6.000000,8.985509,-0.254557,-0.254557,NaN,19044
9044,NaN,NaN,1.0,NaN,NaN,NaN,7.5,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19045

In [62]:
((final[["X", "IR", "pot2"]].isna().sum(axis=1) == 3) + start[["formula", "activity"]].isna().any(axis=1)).sum()

np.int64(5867)

In [63]:
# every (X, ir, pot2) formula property is nan or formula is nan or activity is nan
condition = ~((final[["X", "IR", "pot2"]].isna().sum(axis=1) == 3) +\
              start[["formula", "activity"]].isna().any(axis=1))

In [64]:
final[condition]

,Km,Vmax,activity,X,IR,pot2,ph,temp,dstr,lgCmin,...,TPSA1,TPSA2,TPSA,XLogP,MaxEStateIndex.1,MaxEStateIndex.2,MinPartialCharge.1,MaxPartialCharge.1,BCUT2D_CHGLO,id
7,NaN,NaN,1.0,2.215000,NaN,-0.140000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10008
11,0.020,NaN,1.0,2.750000,1.114286,-0.015429,5.0,55.0,NaN,NaN,...,40.5,52.0,NaN,NaN,6.000000,5.992739,-0.254557,-0.254557,NaN,10012
14,0.010,1.000000e-03,1.0,2.675000,NaN,-0.130000,3.5,50.0,3.0,-0.69897,...,40.5,52.0,NaN,NaN,6.000000,5.992739,-0.254557,-0.254557,NaN,10015
15,0.010,1.000000e-03,1.0,2.675000,NaN,-0.130000,3.5,50.0,3.0,-0.69897,...,52.0,40.5,NaN,NaN,5.992739,6.000000,-0.398299,0.037337,NaN,10016
19,0.150,3.800000e-05,2.0,2.200000,NaN,0.000000,4,25.0,3.0,NaN,...,52.0,34.1,NaN,NaN,5.992739,7.000000,-0.398299,0.037337,NaN,10020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9021,0.050,1.000000e-03,1.0,2.637907,NaN,NaN,3.5,25.0,3.0,-4.30103,...,40.5,52.0,NaN,NaN,6.000000,5.992739,-0.254557,-0.254557,NaN,19022
9025,53.550,1.078000e-07,1.0,2.595556,NaN,0.000000,4.5,37.0,NaN,-inf,...,40.5,52.0,66.5,NaN,6.000000,5.992739,-0.254557,-0.254557,-1.991145,19026
9026,0.213,5.477000e-08,1.0,2.595556,NaN,0.000000,4.5,37.0,NaN,-inf,...,52.0,40.5,66.5,NaN,5.992739,6.000000,-0.398299,0.037337,-1.991145,19027
9027,NaN,NaN,3.0,2.595556,NaN,0.000000,4.5,37.0,NaN,NaN,...,40.5,NaN,66.5,NaN,6.000000,NaN,-0.254557,-0.254557,-1.991145,19028
9036,NaN,NaN,1.0,2.750000,1.114286,-0.015429,5.5,25.0,3.0,NaN,...,NaN,NaN,20.3,0.4,NaN,NaN,NaN,NaN,-2.048433,19037